//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelAnalyzer.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelAnalyzer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О программе.
        /// </summary>
        internal static string About_Button_Description {
            get {
                return ResourceManager.GetString("About_Button_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О программе.
        /// </summary>
        internal static string About_Button_Label {
            get {
                return ResourceManager.GetString("About_Button_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О программе.
        /// </summary>
        internal static string About_Button_ScreenTip {
            get {
                return ResourceManager.GetString("About_Button_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О программе.
        /// </summary>
        internal static string About_Button_SuperTip {
            get {
                return ResourceManager.GetString("About_Button_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление копий листов с соответсвющими алгоритму именами.
        /// </summary>
        internal static string AddSheet_Button_Description {
            get {
                return ResourceManager.GetString("AddSheet_Button_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить листы.
        /// </summary>
        internal static string AddSheet_Button_Label {
            get {
                return ResourceManager.GetString("AddSheet_Button_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление листов для промежуточных результатов.
        /// </summary>
        internal static string AddSheet_Button_ScreenTip {
            get {
                return ResourceManager.GetString("AddSheet_Button_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление листов для промежуточных результатов. Имена листов формируются автоматически согласно алгоритму суммирования..
        /// </summary>
        internal static string AddSheet_Button_SuperTip {
            get {
                return ResourceManager.GetString("AddSheet_Button_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Суммирование значений по алгоритму сложения.
        /// </summary>
        internal static string AutoSum_Button_Description {
            get {
                return ResourceManager.GetString("AutoSum_Button_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Суммировать значения.
        /// </summary>
        internal static string AutoSum_Button_Label {
            get {
                return ResourceManager.GetString("AutoSum_Button_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Суммирование значений по алгоритму сложения.
        /// </summary>
        internal static string AutoSum_Button_ScreenTip {
            get {
                return ResourceManager.GetString("AutoSum_Button_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Суммирование значений по алгоритму сложения с использованием промежуточных результатов..
        /// </summary>
        internal static string AutoSum_Button_SuperTip {
            get {
                return ResourceManager.GetString("AutoSum_Button_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Диалоговое окно для контроля наличия набора именнованных файлов Microsoft Office Excel.
        /// </summary>
        internal static string CheckedFile_Button_Description {
            get {
                return ResourceManager.GetString("CheckedFile_Button_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контроль наличия файлов Microsoft Office Excel....
        /// </summary>
        internal static string CheckedFile_Button_Label {
            get {
                return ResourceManager.GetString("CheckedFile_Button_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контроль наличия файлов Microsoft Office Excel.
        /// </summary>
        internal static string CheckedFile_Button_ScreenTip {
            get {
                return ResourceManager.GetString("CheckedFile_Button_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открывает диалоговое окно для контроля наличия файлов Microsoft Office Excel в коллекции именнованных папок..
        /// </summary>
        internal static string CheckedFile_Button_SuperTip {
            get {
                return ResourceManager.GetString("CheckedFile_Button_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание набора именнованых папок для дальнейшего сбора данных.
        /// </summary>
        internal static string CreateFolders_Button_Description {
            get {
                return ResourceManager.GetString("CreateFolders_Button_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать набор папок для сбора файлов....
        /// </summary>
        internal static string CreateFolders_Button_Label {
            get {
                return ResourceManager.GetString("CreateFolders_Button_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание набора папок для сбора файлов.
        /// </summary>
        internal static string CreateFolders_Button_ScreenTip {
            get {
                return ResourceManager.GetString("CreateFolders_Button_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание набора папок с определенными именами для дальнейшего сбора и обработки данных из файлов Microsoft Office Excel..
        /// </summary>
        internal static string CreateFolders_Button_SuperTip {
            get {
                return ResourceManager.GetString("CreateFolders_Button_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сравнение значений ячеек текущего листа со значениями других листов..
        /// </summary>
        internal static string EqualsSheet_Button_Description {
            get {
                return ResourceManager.GetString("EqualsSheet_Button_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сравнение значений.
        /// </summary>
        internal static string EqualsSheet_Button_Label {
            get {
                return ResourceManager.GetString("EqualsSheet_Button_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сравнение значений.
        /// </summary>
        internal static string EqualsSheet_Button_ScreenTip {
            get {
                return ResourceManager.GetString("EqualsSheet_Button_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сравнение значений ячеек текущего листа со значениями других выбранных листов..
        /// </summary>
        internal static string EqualsSheet_Button_SuperTip {
            get {
                return ResourceManager.GetString("EqualsSheet_Button_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отображение панели анализа данных.
        /// </summary>
        internal static string ExcelAnalyzerPane_Button_Description {
            get {
                return ResourceManager.GetString("ExcelAnalyzerPane_Button_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Панель анализа данных.
        /// </summary>
        internal static string ExcelAnalyzerPane_Button_Label {
            get {
                return ResourceManager.GetString("ExcelAnalyzerPane_Button_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Панель анализа данных.
        /// </summary>
        internal static string ExcelAnalyzerPane_Button_ScreenTip {
            get {
                return ResourceManager.GetString("ExcelAnalyzerPane_Button_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отображение панели анализа данных, позволяющей просматиривать и анализировать  сведения, расположеннные на нескольких листах Microsoft Office Excel..
        /// </summary>
        internal static string ExcelAnalyzerPane_Button_SuperTip {
            get {
                return ResourceManager.GetString("ExcelAnalyzerPane_Button_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт данных в формате СПО АРМ Статистика ГП РФ..
        /// </summary>
        internal static string ExportData_Button_Description {
            get {
                return ResourceManager.GetString("ExportData_Button_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт данных в АРМ Статистика.
        /// </summary>
        internal static string ExportData_Button_Label {
            get {
                return ResourceManager.GetString("ExportData_Button_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт данных в формате АРМ Статистика.
        /// </summary>
        internal static string ExportData_Button_ScreenTip {
            get {
                return ResourceManager.GetString("ExportData_Button_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт данных в формате СПО &quot;Автоматизированное рабочее место &quot;Статистика Генеральной прокуратуры Российской Федерации&quot;..
        /// </summary>
        internal static string ExportData_Button_SuperTip {
            get {
                return ResourceManager.GetString("ExportData_Button_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт формы отчета в формате СПО АРМ Статистика ГП РФ..
        /// </summary>
        internal static string ExportForm_Button_Description {
            get {
                return ResourceManager.GetString("ExportForm_Button_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт формы отчета в АРМ Статистика.
        /// </summary>
        internal static string ExportForm_Button_Label {
            get {
                return ResourceManager.GetString("ExportForm_Button_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт формы отчета в формате АРМ Статистика.
        /// </summary>
        internal static string ExportForm_Button_ScreenTip {
            get {
                return ResourceManager.GetString("ExportForm_Button_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт формы отчета в формате СПО &quot;Автоматизированное рабочее место &quot;Статистика Генеральной прокуратуры Российской Федерации&quot;..
        /// </summary>
        internal static string ExportForm_Button_SuperTip {
            get {
                return ResourceManager.GetString("ExportForm_Button_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт данных в формате СПО АРМ Статистика ГП РФ..
        /// </summary>
        internal static string ExportToARM_Button_Description {
            get {
                return ResourceManager.GetString("ExportToARM_Button_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт данных в АРМ Статистика.
        /// </summary>
        internal static string ExportToARM_Button_Label {
            get {
                return ResourceManager.GetString("ExportToARM_Button_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт данных в формате АРМ Статистика.
        /// </summary>
        internal static string ExportToARM_Button_ScreenTip {
            get {
                return ResourceManager.GetString("ExportToARM_Button_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт данных в формате СПО &quot;Автоматизированное рабочее место &quot;Статистика Генеральной прокуратуры Российской Федерации&quot;..
        /// </summary>
        internal static string ExportToARM_Button_SuperTip {
            get {
                return ResourceManager.GetString("ExportToARM_Button_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Набор комманд для импорта данных.
        /// </summary>
        internal static string File_Button_Description {
            get {
                return ResourceManager.GetString("File_Button_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Работа с файлами.
        /// </summary>
        internal static string File_Button_Label {
            get {
                return ResourceManager.GetString("File_Button_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Работа с файлами.
        /// </summary>
        internal static string File_Button_ScreenTip {
            get {
                return ResourceManager.GetString("File_Button_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Набор комманд для импорта данных.
        /// </summary>
        internal static string File_Button_SuperTip {
            get {
                return ResourceManager.GetString("File_Button_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Импортировать листы из книг Microsoft Office Excel файлов, находящихся в наборе именнованых папок.
        /// </summary>
        internal static string FileImport_Button_Description {
            get {
                return ResourceManager.GetString("FileImport_Button_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Импортировать.
        /// </summary>
        internal static string FileImport_Button_Label {
            get {
                return ResourceManager.GetString("FileImport_Button_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Импорт всех файлов в единую книгу Microsoft Office Excel.
        /// </summary>
        internal static string FileImport_Button_ScreenTip {
            get {
                return ResourceManager.GetString("FileImport_Button_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Импорт всех файлов в единую книгу Microsoft Office Excel. Имена импортированных листов формируются в соответсвии с наименованиями папок в которых расположены соответствующие файлы..
        /// </summary>
        internal static string FileImport_Button_SuperTip {
            get {
                return ResourceManager.GetString("FileImport_Button_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Получение справочных сведений.
        /// </summary>
        internal static string Help_Button_Description {
            get {
                return ResourceManager.GetString("Help_Button_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справка.
        /// </summary>
        internal static string Help_Button_Label {
            get {
                return ResourceManager.GetString("Help_Button_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справка.
        /// </summary>
        internal static string Help_Button_ScreenTip {
            get {
                return ResourceManager.GetString("Help_Button_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Получение справочных сведений.
        /// </summary>
        internal static string Help_Button_SuperTip {
            get {
                return ResourceManager.GetString("Help_Button_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Импортировать листы из книг Microsoft Office Excel файлов, находящихся в наборе именнованых папок.
        /// </summary>
        internal static string Import_Button_Description {
            get {
                return ResourceManager.GetString("Import_Button_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Импорт файлов в единую книгу Microsoft Office Excel....
        /// </summary>
        internal static string Import_Button_Label {
            get {
                return ResourceManager.GetString("Import_Button_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Импорт файлов в единую книгу Microsoft Office Excel.
        /// </summary>
        internal static string Import_Button_ScreenTip {
            get {
                return ResourceManager.GetString("Import_Button_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Импорт файлов в единую книгу Microsoft Office Excel. Имена импортированных листов формируются в соответсвии с наименованиями папок в которых расположены соответствующие файлы..
        /// </summary>
        internal static string Import_Button_SuperTip {
            get {
                return ResourceManager.GetString("Import_Button_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вставка имен листов.
        /// </summary>
        internal static string InsertCaption_Button_Description {
            get {
                return ResourceManager.GetString("InsertCaption_Button_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вставить имена листов.
        /// </summary>
        internal static string InsertCaption_Button_Label {
            get {
                return ResourceManager.GetString("InsertCaption_Button_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вставка имен листов.
        /// </summary>
        internal static string InsertCaption_Button_ScreenTip {
            get {
                return ResourceManager.GetString("InsertCaption_Button_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вставка в выбранную ячейку имен листов.
        /// </summary>
        internal static string InsertCaption_Button_SuperTip {
            get {
                return ResourceManager.GetString("InsertCaption_Button_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копирование содержимого ячеек и вставка.
        /// </summary>
        internal static string InsertCopy_Button_Description {
            get {
                return ResourceManager.GetString("InsertCopy_Button_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копировать и вставить.
        /// </summary>
        internal static string InsertCopy_Button_Label {
            get {
                return ResourceManager.GetString("InsertCopy_Button_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копирование и вставка.
        /// </summary>
        internal static string InsertCopy_Button_ScreenTip {
            get {
                return ResourceManager.GetString("InsertCopy_Button_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копирование содержимого диапазона ячеек в буфер обмена и вставка в соответсвующий диапазон ячеек остальных листов книги Microsoft Office Excel.
        /// </summary>
        internal static string InsertCopy_Button_SuperTip {
            get {
                return ResourceManager.GetString("InsertCopy_Button_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вставка формул в ячейки.
        /// </summary>
        internal static string InsertFormula_Button_Description {
            get {
                return ResourceManager.GetString("InsertFormula_Button_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вставить формулы.
        /// </summary>
        internal static string InsertFormula_Button_Label {
            get {
                return ResourceManager.GetString("InsertFormula_Button_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вставка формул в ячейки.
        /// </summary>
        internal static string InsertFormula_Button_ScreenTip {
            get {
                return ResourceManager.GetString("InsertFormula_Button_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вставка в выбранную ячейку формулы.
        /// </summary>
        internal static string InsertFormula_Button_SuperTip {
            get {
                return ResourceManager.GetString("InsertFormula_Button_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вставка текста в ячейки.
        /// </summary>
        internal static string InsertText_Button_Description {
            get {
                return ResourceManager.GetString("InsertText_Button_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вставить текст.
        /// </summary>
        internal static string InsertText_Button_Label {
            get {
                return ResourceManager.GetString("InsertText_Button_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вставка текста в ячейки.
        /// </summary>
        internal static string InsertText_Button_ScreenTip {
            get {
                return ResourceManager.GetString("InsertText_Button_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вставка в выбранную ячейку текста.
        /// </summary>
        internal static string InsertText_Button_SuperTip {
            get {
                return ResourceManager.GetString("InsertText_Button_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Формирование листа, содержащего построчный срез значений..
        /// </summary>
        internal static string List_Button_Description {
            get {
                return ResourceManager.GetString("List_Button_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Построчный срез.
        /// </summary>
        internal static string List_Button_Label {
            get {
                return ResourceManager.GetString("List_Button_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Формирование построчного среза.
        /// </summary>
        internal static string List_Button_ScreenTip {
            get {
                return ResourceManager.GetString("List_Button_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для построчного среза необходимо: 1. На листе итоговых значений выделить необходимыю ячейку. В результате в книгу будет добавлен лист в котором в качестве строк будут отражены заголовки листов, а в качестве граф показатели строк листа итоговых значений..
        /// </summary>
        internal static string List_Button_SuperTip {
            get {
                return ResourceManager.GetString("List_Button_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Работа с данными СПО АРМ &quot;Статистика ГП РФ&quot;..
        /// </summary>
        internal static string OpenArm_Button_Description {
            get {
                return ResourceManager.GetString("OpenArm_Button_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Работа с данными АРМ Статистика.
        /// </summary>
        internal static string OpenArm_Button_Label {
            get {
                return ResourceManager.GetString("OpenArm_Button_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Работа с данными СПО АРМ &quot;Статистика ГП РФ&quot;.
        /// </summary>
        internal static string OpenArm_Button_ScreenTip {
            get {
                return ResourceManager.GetString("OpenArm_Button_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Работа с данными СПО &quot;Автоматизированное рабочее место &quot;Статистика Генеральной прокуратуры Российской Федерации&quot;..
        /// </summary>
        internal static string OpenArm_Button_SuperTip {
            get {
                return ResourceManager.GetString("OpenArm_Button_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Набор комманд для группировки данных.
        /// </summary>
        internal static string Sheet_Button_Description {
            get {
                return ResourceManager.GetString("Sheet_Button_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Группировка.
        /// </summary>
        internal static string Sheet_Button_Label {
            get {
                return ResourceManager.GetString("Sheet_Button_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Группировка.
        /// </summary>
        internal static string Sheet_Button_ScreenTip {
            get {
                return ResourceManager.GetString("Sheet_Button_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Набор комманд для группировки данных в соответсвии с алгоритмом суммирования..
        /// </summary>
        internal static string Sheet_Button_SuperTip {
            get {
                return ResourceManager.GetString("Sheet_Button_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сортировка листов по алфавиту либо по алгоритму.
        /// </summary>
        internal static string SortDialog_Button_Description {
            get {
                return ResourceManager.GetString("SortDialog_Button_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сортировать листы....
        /// </summary>
        internal static string SortDialog_Button_Label {
            get {
                return ResourceManager.GetString("SortDialog_Button_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сортировка листов.
        /// </summary>
        internal static string SortDialog_Button_ScreenTip {
            get {
                return ResourceManager.GetString("SortDialog_Button_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сортировка листов в книге либо по алфавиту, либо по алгоритму..
        /// </summary>
        internal static string SortDialog_Button_SuperTip {
            get {
                return ResourceManager.GetString("SortDialog_Button_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Суммирование значений ячеек со всех листов кроме текущего..
        /// </summary>
        internal static string Sum_Button_Description {
            get {
                return ResourceManager.GetString("Sum_Button_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Суммировать значения.
        /// </summary>
        internal static string Sum_Button_Label {
            get {
                return ResourceManager.GetString("Sum_Button_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Суммирование значений.
        /// </summary>
        internal static string Sum_Button_ScreenTip {
            get {
                return ResourceManager.GetString("Sum_Button_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для суммирования значений ячеек со всех листов необходимо: 1. Добавить лист для итоговых значений. 2. Выделить на листе итоговых значений требуемый диапазон. В результате значения со всех листов будут суммированы и их сумма будет отражена на листе итоговых значений..
        /// </summary>
        internal static string Sum_Button_SuperTip {
            get {
                return ResourceManager.GetString("Sum_Button_SuperTip", resourceCulture);
            }
        }
    }
}
